<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Detect" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
      <xs:element name="setLandMark">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="lm1" nillable="true" type="xs:string" />
            <xs:element minOccurs="0" name="lm2" nillable="true" type="xs:string" />
            <xs:element minOccurs="0" name="lm3" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="setLandMarkResponse">
        <xs:complexType>
          <xs:sequence />
        </xs:complexType>
      </xs:element>
      <xs:element name="setPingCounter">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="p" type="xs:int" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="setPingCounterResponse">
        <xs:complexType>
          <xs:sequence />
        </xs:complexType>
      </xs:element>
      <xs:element name="resetPingCounter">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="p" type="xs:int" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="resetPingCounterResponse">
        <xs:complexType>
          <xs:sequence />
        </xs:complexType>
      </xs:element>
      <xs:element name="setThreshold">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="t" type="xs:double" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="setThresholdResponse">
        <xs:complexType>
          <xs:sequence />
        </xs:complexType>
      </xs:element>
      <xs:element name="calculateAvgLatency">
        <xs:complexType>
          <xs:sequence />
        </xs:complexType>
      </xs:element>
      <xs:element name="calculateAvgLatencyResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" minOccurs="0" name="calculateAvgLatencyResult" nillable="true" type="q1:ArrayOfdouble" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="calculateMinThreshold">
        <xs:complexType>
          <xs:sequence />
        </xs:complexType>
      </xs:element>
      <xs:element name="calculateMinThresholdResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q2="http://schemas.microsoft.com/2003/10/Serialization/Arrays" minOccurs="0" name="calculateMinThresholdResult" nillable="true" type="q2:ArrayOfdouble" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="calculateMaxThreshold">
        <xs:complexType>
          <xs:sequence />
        </xs:complexType>
      </xs:element>
      <xs:element name="calculateMaxThresholdResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q3="http://schemas.microsoft.com/2003/10/Serialization/Arrays" minOccurs="0" name="calculateMaxThresholdResult" nillable="true" type="q3:ArrayOfdouble" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="reCalculateAvgLatency">
        <xs:complexType>
          <xs:sequence />
        </xs:complexType>
      </xs:element>
      <xs:element name="reCalculateAvgLatencyResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q4="http://schemas.microsoft.com/2003/10/Serialization/Arrays" minOccurs="0" name="reCalculateAvgLatencyResult" nillable="true" type="q4:ArrayOfdouble" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="anyType" nillable="true" type="xs:anyType" />
      <xs:element name="anyURI" nillable="true" type="xs:anyURI" />
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary" />
      <xs:element name="boolean" nillable="true" type="xs:boolean" />
      <xs:element name="byte" nillable="true" type="xs:byte" />
      <xs:element name="dateTime" nillable="true" type="xs:dateTime" />
      <xs:element name="decimal" nillable="true" type="xs:decimal" />
      <xs:element name="double" nillable="true" type="xs:double" />
      <xs:element name="float" nillable="true" type="xs:float" />
      <xs:element name="int" nillable="true" type="xs:int" />
      <xs:element name="long" nillable="true" type="xs:long" />
      <xs:element name="QName" nillable="true" type="xs:QName" />
      <xs:element name="short" nillable="true" type="xs:short" />
      <xs:element name="string" nillable="true" type="xs:string" />
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte" />
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt" />
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong" />
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort" />
      <xs:element name="char" nillable="true" type="tns:char" />
      <xs:simpleType name="char">
        <xs:restriction base="xs:int" />
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration" />
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid" />
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName" />
      <xs:attribute name="Id" type="xs:ID" />
      <xs:attribute name="Ref" type="xs:IDREF" />
    </xs:schema>
    <xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:complexType name="ArrayOfdouble">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="double" type="xs:double" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfdouble" nillable="true" type="tns:ArrayOfdouble" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="IDetect_setLandMark_InputMessage">
    <wsdl:part name="parameters" element="tns:setLandMark" />
  </wsdl:message>
  <wsdl:message name="IDetect_setLandMark_OutputMessage">
    <wsdl:part name="parameters" element="tns:setLandMarkResponse" />
  </wsdl:message>
  <wsdl:message name="IDetect_setPingCounter_InputMessage">
    <wsdl:part name="parameters" element="tns:setPingCounter" />
  </wsdl:message>
  <wsdl:message name="IDetect_setPingCounter_OutputMessage">
    <wsdl:part name="parameters" element="tns:setPingCounterResponse" />
  </wsdl:message>
  <wsdl:message name="IDetect_resetPingCounter_InputMessage">
    <wsdl:part name="parameters" element="tns:resetPingCounter" />
  </wsdl:message>
  <wsdl:message name="IDetect_resetPingCounter_OutputMessage">
    <wsdl:part name="parameters" element="tns:resetPingCounterResponse" />
  </wsdl:message>
  <wsdl:message name="IDetect_setThreshold_InputMessage">
    <wsdl:part name="parameters" element="tns:setThreshold" />
  </wsdl:message>
  <wsdl:message name="IDetect_setThreshold_OutputMessage">
    <wsdl:part name="parameters" element="tns:setThresholdResponse" />
  </wsdl:message>
  <wsdl:message name="IDetect_calculateAvgLatency_InputMessage">
    <wsdl:part name="parameters" element="tns:calculateAvgLatency" />
  </wsdl:message>
  <wsdl:message name="IDetect_calculateAvgLatency_OutputMessage">
    <wsdl:part name="parameters" element="tns:calculateAvgLatencyResponse" />
  </wsdl:message>
  <wsdl:message name="IDetect_calculateMinThreshold_InputMessage">
    <wsdl:part name="parameters" element="tns:calculateMinThreshold" />
  </wsdl:message>
  <wsdl:message name="IDetect_calculateMinThreshold_OutputMessage">
    <wsdl:part name="parameters" element="tns:calculateMinThresholdResponse" />
  </wsdl:message>
  <wsdl:message name="IDetect_calculateMaxThreshold_InputMessage">
    <wsdl:part name="parameters" element="tns:calculateMaxThreshold" />
  </wsdl:message>
  <wsdl:message name="IDetect_calculateMaxThreshold_OutputMessage">
    <wsdl:part name="parameters" element="tns:calculateMaxThresholdResponse" />
  </wsdl:message>
  <wsdl:message name="IDetect_reCalculateAvgLatency_InputMessage">
    <wsdl:part name="parameters" element="tns:reCalculateAvgLatency" />
  </wsdl:message>
  <wsdl:message name="IDetect_reCalculateAvgLatency_OutputMessage">
    <wsdl:part name="parameters" element="tns:reCalculateAvgLatencyResponse" />
  </wsdl:message>
  <wsdl:portType name="IDetect">
    <wsdl:operation name="setLandMark">
      <wsdl:input wsaw:Action="http://tempuri.org/IDetect/setLandMark" message="tns:IDetect_setLandMark_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IDetect/setLandMarkResponse" message="tns:IDetect_setLandMark_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="setPingCounter">
      <wsdl:input wsaw:Action="http://tempuri.org/IDetect/setPingCounter" message="tns:IDetect_setPingCounter_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IDetect/setPingCounterResponse" message="tns:IDetect_setPingCounter_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="resetPingCounter">
      <wsdl:input wsaw:Action="http://tempuri.org/IDetect/resetPingCounter" message="tns:IDetect_resetPingCounter_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IDetect/resetPingCounterResponse" message="tns:IDetect_resetPingCounter_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="setThreshold">
      <wsdl:input wsaw:Action="http://tempuri.org/IDetect/setThreshold" message="tns:IDetect_setThreshold_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IDetect/setThresholdResponse" message="tns:IDetect_setThreshold_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="calculateAvgLatency">
      <wsdl:input wsaw:Action="http://tempuri.org/IDetect/calculateAvgLatency" message="tns:IDetect_calculateAvgLatency_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IDetect/calculateAvgLatencyResponse" message="tns:IDetect_calculateAvgLatency_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="calculateMinThreshold">
      <wsdl:input wsaw:Action="http://tempuri.org/IDetect/calculateMinThreshold" message="tns:IDetect_calculateMinThreshold_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IDetect/calculateMinThresholdResponse" message="tns:IDetect_calculateMinThreshold_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="calculateMaxThreshold">
      <wsdl:input wsaw:Action="http://tempuri.org/IDetect/calculateMaxThreshold" message="tns:IDetect_calculateMaxThreshold_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IDetect/calculateMaxThresholdResponse" message="tns:IDetect_calculateMaxThreshold_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="reCalculateAvgLatency">
      <wsdl:input wsaw:Action="http://tempuri.org/IDetect/reCalculateAvgLatency" message="tns:IDetect_reCalculateAvgLatency_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IDetect/reCalculateAvgLatencyResponse" message="tns:IDetect_reCalculateAvgLatency_OutputMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_IDetect" type="tns:IDetect">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="setLandMark">
      <soap:operation soapAction="http://tempuri.org/IDetect/setLandMark" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="setPingCounter">
      <soap:operation soapAction="http://tempuri.org/IDetect/setPingCounter" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="resetPingCounter">
      <soap:operation soapAction="http://tempuri.org/IDetect/resetPingCounter" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="setThreshold">
      <soap:operation soapAction="http://tempuri.org/IDetect/setThreshold" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="calculateAvgLatency">
      <soap:operation soapAction="http://tempuri.org/IDetect/calculateAvgLatency" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="calculateMinThreshold">
      <soap:operation soapAction="http://tempuri.org/IDetect/calculateMinThreshold" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="calculateMaxThreshold">
      <soap:operation soapAction="http://tempuri.org/IDetect/calculateMaxThreshold" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="reCalculateAvgLatency">
      <soap:operation soapAction="http://tempuri.org/IDetect/reCalculateAvgLatency" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Detect">
    <wsdl:port name="BasicHttpBinding_IDetect" binding="tns:BasicHttpBinding_IDetect">
      <soap:address location="http://migration.com:8080/Detect.svc" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>